const KEY='control-financiero-v1';
const seed={
 debts:[
  {id:1,name:'Eduardo Zavaleta',balance:500,rate:10,payment:50,day:30,type:'Prestamista',priority:'Alta',note:'Pago actual solo de interés; no ha bajado capital.'},
  {id:2,name:'Brenda',balance:500,rate:10,payment:50,day:21,type:'Prestamista',priority:'Alta',note:'Pago actual solo de interés; no ha bajado capital.'},
  {id:3,name:'Niña Claudia #1',balance:540,rate:0,payment:90,day:15,type:'Cuotas fijas',priority:'Mantener',note:'6 cuotas de $90 pendientes para terminar.'},
  {id:4,name:'Niña Claudia #2',balance:200,rate:10,payment:20,day:15,type:'Prestamista',priority:'Alta',note:'Préstamo reciente de $200; por ahora $20 de interés mensual.'},
  {id:5,name:'Prado',balance:203,rate:0,payment:26,day:21,type:'Electrodomésticos',priority:'Alta',note:'Saldo aproximado; quedan ~$203.'},
  {id:6,name:'Agencias Way',balance:230.85,rate:0,payment:25.65,day:28,type:'Electrodomésticos',priority:'Mantener',note:'9 cuotas pendientes de $25.65.'},
  {id:7,name:'Diimo',balance:79.26,rate:0,payment:0,day:null,type:'Aplicación',priority:'Alta',note:'Deuda vencida; sin fecha fija.'},
  {id:8,name:'Prestamista amigo #1',balance:75,rate:10,payment:7.5,day:21,type:'Prestamista',priority:'Alta',note:'Pago actual solo de interés.'},
  {id:9,name:'Prestamista amigo #2',balance:150,rate:10,payment:15,day:21,type:'Prestamista',priority:'Alta',note:'Pago actual solo de interés.'},
  {id:10,name:'ACOPASS',balance:null,rate:0,payment:139,day:9,type:'Cooperativa',priority:'Mantener',note:'Saldo no registrado; mantener cuota mensual.'},
  {id:11,name:'Pininos',balance:200,rate:10,payment:50,day:15,type:'Prestamista',priority:'Alta',note:'$25 el 15 y $25 el 30 de cada mes.'},
  {id:12,name:'David Celulares',balance:60,rate:0,payment:0,day:null,type:'Servicio',priority:'Alta',note:'Reparación de teléfono.'},
  {id:13,name:'Tarjeta Siman',balance:1100,rate:0,payment:60,day:null,type:'Tarjeta',priority:'Media',note:'Tarjeta topada; mínimo aproximado $60 y al día.'},
  {id:14,name:'Tarjeta BAC',balance:450,rate:0,payment:30,day:null,type:'Tarjeta',priority:'Media',note:'Saldo actual ~$450; límite $1,000. Se contempla retiro de $139 para ACOPASS.'}
 ],
 payments:[], incomes:[{id:1,date:'2026-09-21',amount:635,type:'Salario',note:'Ingreso fijo'}], expenses:[
  {id:1,name:'Comida',amount:75,day:null},{id:2,name:'Gasolina',amount:60,day:null},{id:3,name:'Luz',amount:15,day:null},{id:4,name:'Internet',amount:25,day:null},
  {id:5,name:'Spotify',amount:11,day:null},{id:6,name:'Netflix',amount:8,day:null},{id:7,name:'Google One',amount:4,day:null},{id:8,name:'ChatGPT',amount:5,day:null}
 ],settings:{salary:635,extraAverage:200,goalDate:'2026-12-31',cashReserve:50}
};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function money(n){return n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)}
function totalKnown(){return db.debts.reduce((s,d)=>s+(d.balance||0),0)}
function paidTotal(){return db.payments.reduce((s,p)=>s+p.amount,0)}
function monthlyDebt(){return db.debts.reduce((s,d)=>s+(d.payment||0),0)}
function priorityClass(p){return p==='Alta'?'high':p==='Media'?'medium':'low'}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function nextPayments(){const now=new Date();const day=now.getDate();return db.debts.filter(d=>d.day).map(d=>{let date=new Date(now.getFullYear(),now.getMonth(),d.day);if(d.day<day)date=new Date(now.getFullYear(),now.getMonth()+1,d.day);return {...d,date}}).sort((a,b)=>a.date-b.date)}
function renderDashboard(){
 const debt=totalKnown(), paid=paidTotal(), pct=debt?Math.min(100,(paid/debt)*100):0, upcoming=nextPayments().slice(0,6);
 const monthlyFixed=635; const base=175, subs=28;
 document.querySelector('#app').innerHTML=`<div class="grid stats">
  <div class="card"><div class="stat-label">Deuda conocida</div><div class="stat-value">${money(debt)}</div><div class="stat-sub">ACOPASS sin saldo registrado</div></div>
  <div class="card"><div class="stat-label">Pagos registrados</div><div class="stat-value">${money(paid)}</div><div class="stat-sub">Desde que empezaste a usar el sistema</div></div>
  <div class="card"><div class="stat-label">Compromisos mensuales</div><div class="stat-value">${money(monthlyDebt())}</div><div class="stat-sub">Cuotas/intereses conocidos</div></div>
  <div class="card"><div class="stat-label">Ingreso fijo</div><div class="stat-value">${money(monthlyFixed)}</div><div class="stat-sub">+ extras variables ~${money(db.settings.extraAverage)}</div></div>
 </div>
 <div class="grid dashboard-grid">
  <div class="card"><div class="section-title"><h2>Progreso de salida</h2><span class="muted">Meta: diciembre 2026</span></div><div class="big-progress">${pct.toFixed(0)}%</div><div class="progress"><span style="width:${pct}%"></span></div><div class="row"><span>Deuda registrada inicialmente</span><b>${money(debt+paid)}</b></div><div class="row"><span>Pagado</span><b class="good-text">${money(paid)}</b></div><div class="row"><span>Restante conocido</span><b>${money(debt)}</b></div></div>
  <div class="card"><div class="section-title"><h2>Próximos pagos</h2><button class="secondary small" onclick="go('calendario')">Ver todos</button></div><div class="list">${upcoming.map(d=>`<div class="row"><div><b>${d.name}</b><div class="muted">${d.date.toLocaleDateString('es-SV',{day:'2-digit',month:'short'})}</div></div><div class="money">${money(d.payment)}</div></div>`).join('')||'<div class="empty">No hay pagos con fecha.</div>'}</div></div>
 </div>
 <div class="grid dashboard-grid">
  <div class="card"><div class="section-title"><h2>Objetivos de ataque</h2><span class="badge high">Prioridad</span></div><div class="list">${db.debts.filter(d=>d.priority==='Alta').sort((a,b)=>(a.balance||999999)-(b.balance||999999)).slice(0,5).map(d=>`<div class="row"><div><b>${d.name}</b><div class="muted">${d.note||''}</div></div><span class="badge high">${money(d.balance)}</span></div>`).join('')}</div></div>
  <div class="card"><div class="section-title"><h2>Presupuesto base</h2></div><div class="row"><span>Gastos básicos</span><b>${money(base)}</b></div><div class="row"><span>Suscripciones</span><b>${money(subs)}</b></div><div class="row"><span>Disponible antes de deudas</span><b>${money(635-base-subs)}</b></div><div class="muted" style="margin-top:10px">Los ingresos extra se tratan como dinero de ataque, no como ingreso fijo.</div></div>
 </div>`;
}
function renderDebts(){document.querySelector('#app').innerHTML=`<div class="card page-card"><div class="section-title"><h2>Todas las deudas</h2><button class="primary" onclick="openDebt()">+ Nueva deuda</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Deuda</th><th>Saldo</th><th>Interés</th><th>Pago</th><th>Día</th><th>Prioridad</th><th></th></tr></thead><tbody>${db.debts.map(d=>`<tr><td><b>${d.name}</b><div class="muted">${d.type}</div></td><td>${money(d.balance)}</td><td>${d.rate?d.rate+'%':'—'}</td><td>${money(d.payment)}</td><td>${d.day||'—'}</td><td><span class="badge ${priorityClass(d.priority)}">${d.priority}</span></td><td class="actions"><button class="secondary small" onclick="openDebt(${d.id})">Editar</button><button class="danger small" onclick="deleteDebt(${d.id})">Borrar</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderPayments(){document.querySelector('#app').innerHTML=`<div class="card page-card"><div class="section-title"><h2>Historial de pagos</h2><button class="primary" onclick="openPayment()">+ Registrar pago</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Deuda</th><th>Monto</th><th>Capital</th><th>Nota</th></tr></thead><tbody>${db.payments.slice().reverse().map(p=>`<tr><td>${p.date}</td><td><b>${db.debts.find(d=>d.id===p.debtId)?.name||'Eliminada'}</b></td><td>${money(p.amount)}</td><td>${money(p.capital)}</td><td>${p.note||''}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Todavía no hay pagos registrados.</td></tr>'}</tbody></table></div></div>`}
function renderCalendar(){const now=new Date();const year=now.getFullYear(),month=now.getMonth();const first=new Date(year,month,1).getDay();const days=new Date(year,month+1,0).getDate();let cells='';for(let i=0;i<(first||7)-1;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const events=db.debts.filter(x=>x.day===d);cells+=`<div class="day"><div class="day-num">${d}</div>${events.map(e=>`<div class="event">${e.name}<br><b>${money(e.payment)}</b></div>`).join('')}</div>`}document.querySelector('#app').innerHTML=`<div class="card page-card"><div class="section-title"><h2>${now.toLocaleDateString('es-SV',{month:'long',year:'numeric'})}</h2><span class="muted">Fechas de pago</span></div><div class="calendar">${cells}</div></div>`}
function renderIncomes(){document.querySelector('#app').innerHTML=`<div class="card page-card"><div class="section-title"><h2>Ingresos</h2><button class="primary" onclick="openIncome()">+ Registrar ingreso</button></div><div class="row"><span>Ingreso fijo mensual</span><b>${money(db.settings.salary)}</b></div><div class="row"><span>Extras promedio</span><b>${money(db.settings.extraAverage)}</b></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Tipo</th><th>Monto</th><th>Nota</th></tr></thead><tbody>${db.incomes.slice().reverse().map(x=>`<tr><td>${x.date}</td><td>${x.type}</td><td>${money(x.amount)}</td><td>${x.note||''}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderExpenses(){document.querySelector('#app').innerHTML=`<div class="card page-card"><div class="section-title"><h2>Gastos mensuales</h2><button class="primary" onclick="openExpense()">+ Nuevo gasto</button></div><div class="row"><span>Total registrado</span><b>${money(db.expenses.reduce((s,x)=>s+x.amount,0))}</b></div><div class="table-wrap"><table class="table"><thead><tr><th>Concepto</th><th>Monto</th><th></th></tr></thead><tbody>${db.expenses.map(x=>`<tr><td>${x.name}</td><td>${money(x.amount)}</td><td><button class="danger small" onclick="deleteExpense(${x.id})">Borrar</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderStrategy(){const targets=db.debts.filter(d=>d.priority==='Alta'&&d.balance!=null).sort((a,b)=>(a.balance||0)-(b.balance||0));document.querySelector('#app').innerHTML=`<div class="grid dashboard-grid"><div class="card"><div class="section-title"><h2>Estrategia actual</h2><span class="badge high">Plan A</span></div><p>1. Mantener ACOPASS, Way y cuotas estructuradas al día.<br>2. No vaciar el efectivo de supervivencia.<br>3. Usar trabajos extra como fondo de ataque.<br>4. Liquidar primero deudas pequeñas que liberan flujo.<br>5. Después atacar los préstamos al 10%.</p><div class="section-title"><h2>Orden preliminar</h2></div><div class="list">${targets.map((d,i)=>`<div class="row"><span><b>#${i+1} ${d.name}</b><div class="muted">${d.rate?d.rate+'% · ':''}${d.note||''}</div></span><b>${money(d.balance)}</b></div>`).join('')}</div></div><div class="card"><div class="section-title"><h2>Simulador rápido</h2></div><p class="muted">Escribí cuánto dinero extra tenés disponible y el sistema propone el objetivo más pequeño.</p><div class="field"><label>Dinero extra</label><input id="attackAmount" type="number" min="0" step="0.01" value="100"></div><button class="primary" style="margin-top:12px" onclick="simulate()">Calcular ataque</button><div id="simulation" style="margin-top:15px"></div></div></div>`}
function renderSettings(){document.querySelector('#app').innerHTML=`<div class="card page-card"><h2>Configuración</h2><p class="muted">El sistema V1 guarda los datos en el navegador. No pongás contraseñas, números de tarjeta ni datos bancarios completos.</p><div class="form-grid"><div class="field"><label>Ingreso fijo</label><input id="salary" type="number" value="${db.settings.salary}"></div><div class="field"><label>Extras promedio</label><input id="extra" type="number" value="${db.settings.extraAverage}"></div><div class="field"><label>Reserva mínima</label><input id="reserve" type="number" value="${db.settings.cashReserve}"></div></div><div class="modal-actions"><button class="primary" onclick="saveSettings()">Guardar</button><button class="secondary" onclick="exportData()">Exportar respaldo</button><button class="danger" onclick="resetData()">Restaurar datos iniciales</button></div></div>`}
function go(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:'Dashboard',deudas:'Deudas',pagos:'Pagos',calendario:'Calendario',ingresos:'Ingresos',gastos:'Gastos',estrategia:'Estrategia',ajustes:'Ajustes'};document.querySelector('#page-title').textContent=titles[view];({dashboard:renderDashboard,deudas:renderDebts,pagos:renderPayments,calendario:renderCalendar,ingresos:renderIncomes,gastos:renderExpenses,estrategia:renderStrategy,ajustes:renderSettings}[view]||renderDashboard)()}
function openModal(title,html,submit){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-form').innerHTML=html;document.querySelector('#modal-form').onsubmit=e=>{e.preventDefault();submit(new FormData(e.target))};document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden')}
function openDebt(id){const d=db.debts.find(x=>x.id===id)||{};openModal(id?'Editar deuda':'Nueva deuda',`<div class="form-grid"><div class="field"><label>Nombre</label><input name="name" required value="${d.name||''}"></div><div class="field"><label>Saldo</label><input name="balance" type="number" step="0.01" value="${d.balance??''}"></div><div class="field"><label>Interés mensual %</label><input name="rate" type="number" step="0.01" value="${d.rate||0}"></div><div class="field"><label>Pago mensual</label><input name="payment" type="number" step="0.01" value="${d.payment||0}"></div><div class="field"><label>Día de pago</label><input name="day" type="number" min="1" max="31" value="${d.day||''}"></div><div class="field"><label>Prioridad</label><select name="priority"><option ${d.priority==='Alta'?'selected':''}>Alta</option><option ${d.priority==='Media'?'selected':''}>Media</option><option ${d.priority==='Mantener'?'selected':''}>Mantener</option></select></div><div class="field full"><label>Nota</label><input name="note" value="${d.note||''}"></div></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary">Guardar</button></div>`,f=>{const obj={id:id||Date.now(),name:f.get('name'),balance:f.get('balance')===''?null:Number(f.get('balance')),rate:Number(f.get('rate')||0),payment:Number(f.get('payment')||0),day:f.get('day')?Number(f.get('day')):null,type:d.type||'Personal',priority:f.get('priority'),note:f.get('note')};if(id)db.debts=db.debts.map(x=>x.id===id?obj:x);else db.debts.push(obj);save();closeModal();renderDebts();toast('Deuda guardada')})}
function deleteDebt(id){if(confirm('¿Borrar esta deuda?')){db.debts=db.debts.filter(x=>x.id!==id);save();renderDebts();toast('Deuda eliminada')}}
function openPayment(){openModal('Registrar pago',`<div class="form-grid"><div class="field"><label>Deuda</label><select name="debtId" required>${db.debts.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></div><div class="field"><label>Fecha</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Monto total</label><input name="amount" type="number" step="0.01" required></div><div class="field"><label>Capital abonado</label><input name="capital" type="number" step="0.01" value="0"></div><div class="field full"><label>Nota</label><input name="note"></div></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary">Registrar</button></div>`,f=>{const debtId=Number(f.get('debtId')),amount=Number(f.get('amount')),capital=Number(f.get('capital')||0),d=db.debts.find(x=>x.id===debtId);if(d.balance!=null)d.balance=Math.max(0,d.balance-capital);db.payments.push({id:Date.now(),debtId,date:f.get('date'),amount,capital,note:f.get('note')});save();closeModal();renderPayments();toast('Pago registrado y saldo actualizado')})}
function openIncome(){openModal('Registrar ingreso',`<div class="form-grid"><div class="field"><label>Fecha</label><input name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Monto</label><input name="amount" type="number" step="0.01" required></div><div class="field"><label>Tipo</label><select name="type"><option>Trabajo extra</option><option>Salario</option><option>Otro</option></select></div><div class="field"><label>Nota</label><input name="note"></div></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary">Guardar</button></div>`,f=>{db.incomes.push({id:Date.now(),date:f.get('date'),amount:Number(f.get('amount')),type:f.get('type'),note:f.get('note')});save();closeModal();renderIncomes();toast('Ingreso registrado')})}
function openExpense(){openModal('Nuevo gasto mensual',`<div class="form-grid"><div class="field"><label>Concepto</label><input name="name" required></div><div class="field"><label>Monto</label><input name="amount" type="number" step="0.01" required></div></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary">Guardar</button></div>`,f=>{db.expenses.push({id:Date.now(),name:f.get('name'),amount:Number(f.get('amount'))});save();closeModal();renderExpenses();toast('Gasto agregado')})}
function deleteExpense(id){db.expenses=db.expenses.filter(x=>x.id!==id);save();renderExpenses();toast('Gasto eliminado')}
function simulate(){const a=Number(document.querySelector('#attackAmount').value)||0;const d=db.debts.filter(x=>x.balance!=null&&x.priority==='Alta').sort((x,y)=>x.balance-y.balance)[0];document.querySelector('#simulation').innerHTML=d?`<div class="card" style="background:#f8fafc"><b>Objetivo sugerido: ${d.name}</b><p class="muted">Saldo: ${money(d.balance)} · Disponés de ${money(a)}.</p><b>${a>=d.balance?'Con ese monto podrías liquidarla.':'Todavía faltarían '+money(d.balance-a)+'.'}</b></div>`:'No hay objetivos disponibles.'}
function saveSettings(){db.settings.salary=Number(document.querySelector('#salary').value);db.settings.extraAverage=Number(document.querySelector('#extra').value);db.settings.cashReserve=Number(document.querySelector('#reserve').value);save();toast('Configuración guardada')}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo-finanzas.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Esto borra los cambios locales y vuelve a los datos iniciales. ¿Continuar?')){db=structuredClone(seed);save();go('dashboard');toast('Datos iniciales restaurados')}}
async function requestNotifications(){if(!('Notification' in window)){toast('Tu navegador no admite notificaciones');return}const p=await Notification.requestPermission();toast(p==='granted'?'Notificaciones activadas':'Permiso de notificaciones no concedido')}
function checkReminders(){if(!('Notification' in window)||Notification.permission!=='granted')return;const today=new Date().getDate();const items=db.debts.filter(d=>d.day&&[today,today+1,today+2,today+3].includes(d.day));items.forEach(d=>new Notification('Recordatorio financiero',{body:`${d.name}: ${money(d.payment)} · vence el día ${d.day}.`}))}
document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));document.querySelector('#quick-payment').onclick=()=>openPayment();document.querySelector('#notify-btn').onclick=requestNotifications;document.querySelector('#close-modal').onclick=closeModal;document.querySelector('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});go('dashboard');checkReminders();
